General PEP compliance, add docs, update ``_quadratic_form`` to ``spins_to_symbols``
jackraymond/dimod pull request #6
Opened 2023-06-22 21:49 UTC by JoelPasvolsky

@jackraymond, this is the first of two general PRs on `mimo.py`. The next one will continue updating internal functions from ``lattice_to_attenuation_matrix`` to ``create_signal`` as needed, add support for 256QAM to all internal functions, and add unittesting for those functions that still don't have it. I'll make separate PRs for updating public functions ``spin_encoded_mimo`` and ``spin_encoded_comp`` in coordination with your King's graph updates. 
Note that currently I'm only adding typing support for public functions (can reconsider later).

2023-06-22 22:01 UTC, JoelPasvolsky commented on dimod/generators/mimo.py
> +    # Jack: you'll need to go over the following carefully
@jackraymond, to help you view this, here's an HTML rendition of the Latex:
![image](https://github.com/jackraymond/dimod/assets/34041130/861f8f4f-8dc7-49f8-b4e7-6a09d24b0a19)

2023-06-29 23:57 UTC, jackraymond commented on dimod/generators/mimo.py
> +    :math:`\\frac{SNR}{N_t} = \\frac{P}{Nt}/N0`
```suggestion
    :math:`\\frac{SNR}{N_t} = \\frac{P}{Nt}/N_0` 
```

2023-06-29 23:58 UTC, jackraymond commented on dimod/generators/mimo.py
> +    :math:`P/N_t I[N_t] = E[v v^{\dagger}] \qquad \Rightarrow \qquad P = <P_c>*N_t`,
```suggestion
    :math:`P/N_t I[N_t] = E[v v^{\dagger}] \qquad \Rightarrow \qquad P = <P_c> N_t`, 
```

2023-06-29 23:59 UTC, jackraymond commented on dimod/generators/mimo.py
> +    :math:`SNRb = \\frac{SNR}{N_t bps}`
```suggestion
    :math:`SNR_b = \\frac{SNR}{N_t bps}`
```

2023-06-29 23:59 UTC, jackraymond commented on dimod/generators/mimo.py
> +    Typical use case: set :math:`\\frac{SNR}{N_t} = SNRb`.
```suggestion
    Typical use case: set :math:`\\frac{SNR}{N_t} = SNR_b`.
```

2023-06-30 00:06 UTC, jackraymond commented on dimod/generators/mimo.py
> +    Following the conventions of MacKay\ [#Mackay]_, a filter is constructed for:
```suggestion
    Following the conventions of MacKay\ [#Mackay]_, a filter is constructed for independent and identically 
    distributed Gaussian noise at power spectral density `N_0`:
```

2023-06-30 00:10 UTC, jackraymond commented on dimod/generators/mimo.py
> +    For independent and identically distributed (i.i.d) elements
```suggestion
    For independent and identically distributed (i.i.d), zero mean, transmitted symbols 
```

2023-06-30 00:12 UTC, jackraymond commented on dimod/generators/mimo.py
> +    :math:`(1, 2, 10, 42)N_t` for BPSK, QPSK, 16QAM, 64QAM,
```suggestion
```

2023-06-30 00:13 UTC, jackraymond commented on dimod/generators/mimo.py
> +    :math:`P/N_t I[N_t] = E[v v^{\dagger}] \qquad \Rightarrow \qquad P = <P_c> N_t`,
```suggestion
    :math:`P_c I[N_t] = E[v v^{\dagger}]`
```

2023-06-30 00:14 UTC, jackraymond commented on dimod/generators/mimo.py
> +    where :math:`<P_{c}>` is the constellation's mean power.
```suggestion
    where :math:`P_{c}` is the constellation's mean power equal to  :math:`(1, 2, 10, 42)N_t` 
    for BPSK, QPSK, 16QAM, 64QAM respectively 
```

2023-06-30 00:16 UTC, jackraymond commented on dimod/generators/mimo.py
> +    :math:`\\frac{SNR}{N_t} = \\frac{P}{Nt}/N_0`
```suggestion
    :math:`\\frac{SNR}{N_t} = \\frac{P_c}{N_0}` 
```

2023-06-30 00:19 UTC, jackraymond commented on dimod/generators/mimo.py
> +    where :math:`bps` is bit per symbol.
```suggestion
    where :math:`B_c` is bit per symbol  equal to  :math:`(1, 2, 4, 8)` 
    for BPSK, QPSK, 16QAM, 64QAM respectively 
```

2023-06-30 00:25 UTC, jackraymond requested changes
docstring changes, hopefully suggestions aren't errant - some simplifications and standardizations. Might require one more iteration at a later point.

2023-06-30 16:32 UTC, merged